services:
  api:
    build:
      context: .
      dockerfile: MotivHealthToDoApi/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./MotivHealthToDoApi:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet: